"""add refresh tokens email verification token version

Revision ID: 1dd630bdd56b
Revises: a1b2c3d4e5f6
Create Date: 2026-03-23 11:02:23.647820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dd630bdd56b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)

    op.drop_table('api_exercises')
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.create_index('idx_activity_comments_activity_id', ['activity_id'], unique=False)

    with op.batch_alter_table('activity_likes', schema=None) as batch_op:
        batch_op.create_index('idx_activity_likes_activity_id', ['activity_id'], unique=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('idx_activity_logs_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index('idx_friendships_friend_status', ['friend_id', 'status'], unique=False)
        batch_op.create_index('idx_friendships_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('idx_goals_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index('idx_habits_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conversation_id', ['conversation_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_user_read', ['user_id', 'is_read'], unique=False)

    with op.batch_alter_table('social_activities', schema=None) as batch_op:
        batch_op.create_index('idx_social_activities_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_verification_token'), ['verification_token'], unique=False)

    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.create_index('idx_weight_logs_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_weight_logs_user_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_token'))
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('token_version')

    with op.batch_alter_table('social_activities', schema=None) as batch_op:
        batch_op.drop_index('idx_social_activities_user_created')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_user_read')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_conversation_id')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index('idx_habits_user_id')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('idx_goals_user_id')

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index('idx_friendships_user_status')
        batch_op.drop_index('idx_friendships_friend_status')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_logs_user_created')

    with op.batch_alter_table('activity_likes', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_likes_activity_id')

    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_comments_activity_id')

    op.create_table('api_exercises',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_muscles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('secondary_muscles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('illustration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_exercises_pkey'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
