"""Add weight tracking and improvements

Revision ID: 6f99b8ad3499
Revises: f1a2b3c4d5e6
Create Date: 2026-03-05 19:24:21.249112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f99b8ad3499'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streak_freezes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streak_freezes_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streak_freezes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streak_freezes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
